quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:app_user}
    password: ${DB_PASSWORD:app_user}
    jdbc:
      url: ${DB_URL:jdbc:postgresql://localhost:15432/app_user}

fruit-rest/mp-rest/url: http://www.fruityvice.com